language: html

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run build --prod

after_success:
  - firebase use xavier
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: change